Задание 2 - вёрстка главной страницы
htmlacademy-adaptive/963049-cat-energy-24 pull request #2
Opened 2021-11-27 06:33 UTC by Enver-B

2021-11-27 14:42 UTC, baronin requested changes
Хорошо :)

2021-11-27 14:42 UTC, baronin commented on source/index.html
> +            <li class="food-benefits__item benefits-content">
food-benefits__item относить к списку  food-benefits__list ?
Если да- то лучше указать food-benefits__list-item

2021-11-27 14:42 UTC, baronin commented on source/index.html
> +            <dl class="example-stats__list">
example-stats - я бы лучше в dl поставил этот класс и дальше у меня был бы example-stats__item -

2021-11-27 14:42 UTC, baronin commented on source/index.html
> +          <form class="live-example__form">
`live-example__form` и рядом я бы сделал блок `live-example-form` и вот застилить по бему уже live-example-form

2021-11-27 14:42 UTC, baronin commented on source/index.html
> +            <fieldset class="live-example__fieldset cat-change">
Думаю тут лучше будет вместо `cat-change` - `range-fieldset`, так как это у нас ренже ) но не очень похоже, что будет по бэму

2021-11-27 14:42 UTC, baronin commented on source/index.html
> +                  <div class="scale">
scale - очень сложно понять по название к какому блоку это относиться

2021-11-27 14:42 UTC, baronin commented on source/index.html
> +      <div class="page-footer__location">
Тут ты мог добавить к page-footer__location - location класс и он был бы блоком для бэма, мне кажеться было бы хорошо

2021-11-27 14:42 UTC, baronin commented on source/index.html
> +                <dt class="example-stats__weight">
Классно что ты используешь тут dl dt :)

2021-11-27 14:42 UTC, baronin commented on source/index.html
> +          <li class="footer-social-networks__item">
footer-social-networks__item - я как понимаю тут айтем относиться к footer-social-networks__list - то и указывай это footer-social-networks__list-item

2021-11-27 14:42 UTC, baronin commented on source/index.html
> +              <li class="footer-developer__item">
Выше пример отписывал

2021-11-27 14:42 UTC, baronin commented on source/index.html
> +              <li class="networks-item">
Это не бэм :)

2021-11-27 14:42 UTC, baronin commented on source/index.html
> +            <ul class="networks-list">
Это не бэм :)

2021-11-27 14:42 UTC, baronin commented on source/img/svg/benefits-icon-1.svg
> +<svg width="61" height="60" viewBox="0 0 61 60" fill="none" xmlns="http://www.w3.org/2000/svg">
Мне кажется, все иконки нужно в папку с иноками положить
svg/icon-social/ imgs
svg/icon-benefits/ imgs
как пример

2021-11-27 15:22 UTC, Enver-B commented on source/index.html
> +            <a href="catalog.html">
исправил

2021-11-27 15:36 UTC, Enver-B commented on source/index.html
> +                <div class="appearance-controls">
исправил, спасибо за ссылку

2021-11-27 15:40 UTC, Enver-B commented on source/index.html
> +            <li class="food-benefits__item benefits-content">
исправил, но так указывали на лекции
![image](https://user-images.githubusercontent.com/70843623/143687751-d9b772cb-5bd2-4e2e-b199-00bfb4fd2099.png)

2021-11-27 15:43 UTC, Enver-B commented on source/index.html
> +            <dl class="example-stats__list">
исправил

2021-11-27 15:54 UTC, Enver-B commented on source/index.html
> +          <form class="live-example__form">
исправил полностью форму, максимально упростил, надеюсь так можно

2021-11-27 15:57 UTC, Enver-B commented on source/index.html
> +            <fieldset class="live-example__fieldset cat-change">
исправил под БЭМ

2021-11-27 15:58 UTC, Enver-B commented on source/index.html
> +                  <div class="scale">
все убрал, форму максимально упростил

2021-11-27 16:01 UTC, Enver-B commented on source/index.html
> +      <div class="page-footer__location">
изменил

2021-11-27 16:01 UTC, Enver-B commented on source/index.html
> +                <dt class="example-stats__weight">
:)

2021-11-27 16:03 UTC, Enver-B commented on source/index.html
> +          <li class="footer-social-networks__item">
исправил

2021-11-27 16:04 UTC, Enver-B commented on source/index.html
> +              <li class="footer-developer__item">
исправил

2021-11-27 16:10 UTC, Enver-B commented on source/index.html
> +              <li class="networks-item">
понял ошибку, исправил)

2021-11-27 16:10 UTC, Enver-B commented on source/index.html
> +            <ul class="networks-list">
тоже исправил

2021-11-27 16:15 UTC, Enver-B commented on source/img/svg/benefits-icon-1.svg
> +<svg width="61" height="60" viewBox="0 0 61 60" fill="none" xmlns="http://www.w3.org/2000/svg">
сделал, хорошая идея, спасибо!

2021-11-27 17:10 UTC, baronin commented on source/index.html
> +            <li class="food-benefits__item benefits-content">
food-benefits__list-item - список ul в нашем случае не может быть food-benefits__list-item, только food-benefits__list
А вот его дочерние элементы уже food-benefits__list-item

2021-11-27 17:11 UTC, baronin commented on source/index.html
> +            <dl class="example-stats__list">
Супер!

2021-11-27 17:14 UTC, baronin commented on source/index.html
> +          <form class="live-example__form">
Извини :) Только увидел что это не форма :)
Тут лейблы тоже излишни

2021-11-28 09:46 UTC, merged

2021-11-28 09:48 UTC, baronin approved these changes