задание 2 - вёрстка страницы формы (версия 1)
htmlacademy-adaptive/963049-cat-energy-24 pull request #3
Opened 2021-11-29 04:47 UTC by Enver-B

2021-11-29 20:49 UTC, baronin requested changes

2021-11-29 20:49 UTC, baronin commented on source/form.html
> +                  <input class="user-field__input-weight" type="text" id="weight" name="weight">
Давай сделаем что бы вес можно было ввести только цифры

2021-11-29 20:49 UTC, baronin commented on source/form.html
> +                  <input class="user-field__input-age" type="text" id="age" name="age">
И тут так же как и с весом :)

2021-11-29 20:49 UTC, baronin commented on source/form.html
> +          <div class="copyright__logo">
я думаю логотипы обычно идут ссылкой

2021-11-29 20:49 UTC, baronin commented on source/catalog.html
> +                        <ul class="card-content__column-first-list column-first-list">
Давай попробуем https://htmlacademy.ru/courses/301/run/6

2021-11-29 20:49 UTC, baronin commented on source/catalog.html
> +          <div class="copyright__logo">
Наверное тут тоже ссылка которая ведет на сайт академии

2021-11-30 09:55 UTC, Enver-B commented on source/form.html
> +                  <input class="user-field__input-weight" type="text" id="weight" name="weight">
исправил

2021-11-30 09:55 UTC, Enver-B commented on source/form.html
> +                  <input class="user-field__input-age" type="text" id="age" name="age">
исправил

2021-11-30 10:50 UTC, Enver-B commented on source/catalog.html
> +                        <ul class="card-content__column-first-list column-first-list">
переделал

2021-11-30 10:51 UTC, Enver-B commented on source/catalog.html
> +          <div class="copyright__logo">
исправил

2021-11-30 18:31 UTC, baronin approved these changes

2021-11-30 18:32 UTC, merged