Задание 3 - Стилизация всех страниц(Версия 1)
htmlacademy-adaptive/963049-cat-energy-24 pull request #4
Opened 2021-12-05 07:25 UTC by Enver-B

2021-12-05 08:54 UTC, baronin requested changes
параметры текста: шрифты, размеры шрифта, межстрочные расстояния, цвет текста;
Это нужно сделать :)

2021-12-05 08:54 UTC, baronin commented on source/catalog.html
> +                <a href="index.html">Главная</a>
В макету у ссылок жирность bold
![image](https://user-images.githubusercontent.com/20131942/144739445-11088b46-f9f2-4829-b46a-2b855ffa640e.png)

2021-12-05 08:54 UTC, baronin commented on source/catalog.html
>      <header class="page-header">
Нет внутренего отступа
![image](https://user-images.githubusercontent.com/20131942/144739494-65ba1c4a-fbee-464a-9c5c-a6918c47ca43.png)

2021-12-05 08:54 UTC, baronin commented on source/sass/blocks/page-index/food-program.scss
> +  padding: 27px 35px 164px 36px;
Таких больших падингов, в нашем случае, не должно быть у этого блока
Да и на хедер это не похоже

2021-12-05 08:54 UTC, baronin commented on source/sass/blocks/page-index/food-program.scss
> +.food-program__image-food {
С absolute пока рано, по этому сейчас этот блок не правильно сверстан

2021-12-05 08:54 UTC, baronin commented on source/index.html
>        <section class="food-program">
У этого блока нету внутренних отступов

2021-12-05 08:54 UTC, baronin commented on source/sass/global/style-text-index.scss
> +.pro-food__title {
pro-food .slim-food - стили одинаковые, почему мы не сделаем один класс ? у нас сейчас идет дублирование

2021-12-05 08:54 UTC, baronin commented on source/sass/global/buttons.scss
> +.food-program__button {
эти классы я бы вынес в тот scss  файл, к которому он относится
А в этом файле сделал общие стили кнопок используемых на сайта
button - дефолтное состояние
button-primary - основная кнопка
button-secondary - второстепенная

2021-12-05 08:54 UTC, baronin commented on source/sass/blocks/page-index/live-example.scss
> +  padding: 25px 0 40px 20px;
Почему решил задать правый падинг 0 ?

2021-12-05 08:54 UTC, baronin commented on source/sass/blocks/footer/page-footer.scss
> +.page-footer__wrapper {
Нету бэкграунда как на макетее

2021-12-05 08:54 UTC, baronin commented on source/sass/global/style-text-index.scss
> +.pro-food__title {
Не заданно семейство шрифта

2021-12-05 08:54 UTC, baronin commented on source/index.html
> +                <p class="slim-food__text">Ваш кот весит больше собаки и<br>
Не задано семейство шрифта

2021-12-05 14:57 UTC, Enver-B commented on source/catalog.html
> +                <a href="index.html">Главная</a>
исправил

2021-12-05 15:03 UTC, Enver-B commented on source/catalog.html
>      <header class="page-header">
добавил

2021-12-05 15:14 UTC, Enver-B commented on source/sass/blocks/page-index/food-program.scss
> +  padding: 27px 35px 164px 36px;
исправил: убрал хедер и исправил паддинги

2021-12-05 15:16 UTC, Enver-B commented on source/index.html
>        <section class="food-program">
его нет на макете, я же его скрыл

2021-12-05 16:06 UTC, Enver-B commented on source/sass/global/style-text-index.scss
> +.pro-food__title {
класс объединил, шрифт задал, но не получается подключить

2021-12-05 17:31 UTC, Enver-B commented on source/sass/global/buttons.scss
> +.food-program__button {
изменил

2021-12-05 17:34 UTC, Enver-B commented on source/sass/blocks/page-index/live-example.scss
> +  padding: 25px 0 40px 20px;
ошибся, наверное. Исправил по макету

2021-12-05 17:36 UTC, Enver-B commented on source/sass/blocks/footer/page-footer.scss
> +.page-footer__wrapper {
исправил

2021-12-05 17:37 UTC, Enver-B commented on source/index.html
> +                <p class="slim-food__text">Ваш кот весит больше собаки и<br>
исправил

2021-12-06 02:38 UTC, Enver-B commented on source/sass/global/style-text-index.scss
> +.pro-food__title {
шрифт подключил

2021-12-08 21:22 UTC, baronin requested changes

2021-12-08 21:22 UTC, baronin commented on source/sass/blocks/page-index/food-program.scss
> +  margin: 3px 20px 20px 20px;
Подскажи, зачем нам тут марджини нужны ?

2021-12-08 21:22 UTC, baronin commented on source/sass/blocks/page-index/options-foods.scss
> +  padding-bottom: 23px;
Тут больше похоже на то, что отступ внешний

2021-12-08 21:22 UTC, baronin commented on source/sass/blocks/page-index/options-foods.scss
> +  padding: 19px 0 22px 0;
![image](https://user-images.githubusercontent.com/20131942/145284618-19af4c71-a43f-42fd-9340-b23ae5517200.png)
Думаю сверху снизу это внешние отступы
И у тебя сейчас происходит схлопывание блоков

2021-12-08 21:22 UTC, baronin commented on source/sass/blocks/page-index/live-example.scss
> +.live-example {
у блока нету внутреннего отступа сверху и снизу
![image](https://user-images.githubusercontent.com/20131942/145285009-ebff163a-b770-4c38-b811-8baa630c2caf.png)

2021-12-08 21:22 UTC, baronin commented on source/form.html
> +    <footer class="page-footer footer-form">
у футера нету отступов сверху и сниху
![image](https://user-images.githubusercontent.com/20131942/145285184-0ad7d725-e325-4eca-93fc-c3e2647f9002.png)

2021-12-09 03:34 UTC, Enver-B commented on source/sass/blocks/page-index/food-program.scss
> +  margin: 3px 20px 20px 20px;
за счет внешних отступов, задаю кнопке отступы от соседних блоков. Но если я правильно понял твое замечание, я задал кнопке обертку div и применил к нему падинги.

2021-12-09 03:40 UTC, Enver-B commented on source/sass/blocks/page-index/options-foods.scss
> +  padding-bottom: 23px;
исправил

2021-12-09 03:42 UTC, Enver-B commented on source/sass/blocks/page-index/options-foods.scss
> +  padding: 19px 0 22px 0;
исправил

2021-12-09 04:05 UTC, Enver-B commented on source/sass/blocks/page-index/live-example.scss
> +.live-example {
так как, я применил отступы не к live-example, а во вложенный в него live-example__wrapper, расстояния между соседними блоками, должны быть как в макете

2021-12-09 04:21 UTC, Enver-B commented on source/form.html
> +    <footer class="page-footer footer-form">
добавил

2021-12-09 06:24 UTC, baronin commented on source/index.html
>        <section class="food-program">
секция food-program у тебя не скрыта

2021-12-09 06:31 UTC, merged