Задание 4 - Адаптивная сетка для главной страницы (Версия 1)
htmlacademy-adaptive/963049-cat-energy-24 pull request #5
Opened 2021-12-11 15:24 UTC by Enver-B

2021-12-12 21:54 UTC, baronin requested changes

2021-12-12 21:54 UTC, baronin commented on source/index.html
>        <div class="page-header__wrapper">
Не отцентрировано
![image](https://user-images.githubusercontent.com/20131942/145730882-96722305-d652-4644-a775-06769607b2c3.png)

2021-12-12 21:54 UTC, baronin commented on source/index.html
>        <div class="page-header__wrapper">
Так же и остальные блоки
![image](https://user-images.githubusercontent.com/20131942/145730974-e26a1397-4570-4c0c-a5fd-b5164441e822.png)

2021-12-14 04:17 UTC, Enver-B commented on source/index.html
>        <div class="page-header__wrapper">
исправил

2021-12-14 16:32 UTC, baronin requested changes

2021-12-14 16:32 UTC, baronin commented on source/sass/blocks/header/page-header.scss
> +@media (min-width: $tablet-width) {
Тут нужно задать класс, что бы медиа веражиние поняло к какому классу нужно применить стили
![image](https://user-images.githubusercontent.com/20131942/146037045-d96da0c8-1c3a-4959-be06-bfd5fb96a4c3.png)

2021-12-14 16:32 UTC, baronin commented on source/index.html
> +          <div class="location__wrapper">
![image](https://user-images.githubusercontent.com/20131942/146038054-4767d412-0ed5-4f95-b8a2-42766bddb216.png)
Под мобильные девайсы так же выглядит![image](https://user-images.githubusercontent.com/20131942/146038054-4767d412-0ed5-4f95-b8a2-42766bddb216.png)![image](https://user-images.githubusercontent.com/20131942/146037907-e85e9657-fe26-4735-b068-31eeda82d732.png)

2021-12-14 16:32 UTC, baronin commented on source/index.html
>          <div class="food-benefits__wrapper">
![image](https://user-images.githubusercontent.com/20131942/146038415-500a6276-fbf2-4037-8c6d-27e8c5078591.png)
Блоки не престраиваются на планшете разрешении 710

2021-12-14 16:32 UTC, baronin commented on source/sass/blocks/page-index/healthy-food.scss
> +  .healthy-food-list {
![image](https://user-images.githubusercontent.com/20131942/146038797-a922102b-347d-4707-b134-8d3aadb6aa7a.png)
Блоки не престраиваются на десктопе

2021-12-14 16:32 UTC, baronin commented on source/index.html
>          <div class="food-program__wrapper">
Блоки не престраиваются на десктопе
![image](https://user-images.githubusercontent.com/20131942/146038966-eeb45038-066e-4ac0-8d12-b60afddbe6ce.png)

2021-12-14 16:32 UTC, baronin commented on source/index.html
>        <section class="live-example">
Блоки не престраиваются на десктопе
![image](https://user-images.githubusercontent.com/20131942/146039093-4f3effdf-3bc6-401f-8b2f-9c66f3670535.png)

2021-12-14 16:32 UTC, baronin commented on source/index.html
>        <div class="page-header__wrapper">
Контенера нету :(
![image](https://user-images.githubusercontent.com/20131942/146039485-823895d5-fb8a-41a1-8d37-eb058fb9011f.png)

2021-12-14 19:35 UTC, Enver-B commented on source/index.html
>        <div class="page-header__wrapper">
исправил

2021-12-14 19:35 UTC, Enver-B commented on source/sass/blocks/header/page-header.scss
> +@media (min-width: $tablet-width) {
исправил

2021-12-14 19:35 UTC, Enver-B commented on source/index.html
> +          <div class="location__wrapper">
исправил

2021-12-14 19:35 UTC, Enver-B commented on source/index.html
>          <div class="food-benefits__wrapper">
исправил

2021-12-14 19:36 UTC, Enver-B commented on source/sass/blocks/page-index/healthy-food.scss
> +  .healthy-food-list {
исправил

2021-12-14 19:36 UTC, Enver-B commented on source/index.html
>          <div class="food-program__wrapper">
исправил

2021-12-14 19:36 UTC, Enver-B commented on source/index.html
>        <section class="live-example">
исправил

2021-12-16 17:19 UTC, merged