задание 6. адаптивная графика всех страниц (версия 1)
htmlacademy-adaptive/963049-cat-energy-24 pull request #9
Opened 2022-01-09 09:14 UTC by Enver-B

2022-01-09 19:22 UTC, baronin requested changes
Хорошо, но еще поработаем :)

2022-01-09 19:22 UTC, baronin commented on source/sass/blocks/page-index/benefits-content.scss
> +    background-image: url("../../../img/png/benefits-content__bg-2.png");
В макете есть название шрифтра и размер цифр, попробуй обойтись без загрузки картинок с цифрами

2022-01-09 19:22 UTC, baronin commented on source/catalog.html
> +                            <img class="catalog-card__image-card" src="img/jpg/catalog-image/catalog-image-mobile-1.jpg" srcset="img/jpg/catalog-image/catalog-image-mobile-1@2x.jpg 2x" width="140" he
Картинки в каталоге идут png - что бы был прозрачный фон, jpg используем для бэкгранудна, фотографии

2022-01-09 19:22 UTC, baronin commented on source/catalog.html
> +                      <div class="catalog-card__other-icon">
Если присмотреться, то это кнопка которая раскрывает 100500 товаров

2022-01-09 19:22 UTC, baronin commented on source/catalog.html
> +                        <img class="catalog-card__image-icon" src="img/svg/icon-catalog/plus-mobile.svg" width="30" height="30" alt="Иконка плюс">
этот крестик легко сделать css что бы не тянуть с сервера картинку 
ну или же лучше использовать svg

2022-01-11 06:41 UTC, Enver-B commented on source/catalog.html
> +                        <img class="catalog-card__image-icon" src="img/svg/icon-catalog/plus-mobile.svg" width="30" height="30" alt="Иконка плюс">
заменил

2022-01-11 06:50 UTC, Enver-B commented on source/catalog.html
> +                      <div class="catalog-card__other-icon">
исправил

2022-01-11 07:57 UTC, Enver-B commented on source/catalog.html
> +                            <img class="catalog-card__image-card" src="img/jpg/catalog-image/catalog-image-mobile-1.jpg" srcset="img/jpg/catalog-image/catalog-image-mobile-1@2x.jpg 2x" width="140" he
исправил

2022-01-11 08:25 UTC, Enver-B commented on source/sass/blocks/page-index/benefits-content.scss
> +    background-image: url("../../../img/png/benefits-content__bg-2.png");
сделал

2022-01-11 08:37 UTC, Enver-B commented on source/catalog.html
>            <a class="page-header__logo">
добавил

2022-01-11 11:55 UTC, Enver-B commented on source/catalog.html
>            <a class="page-header__logo">
исправил

2022-01-19 07:34 UTC, merged